### ISSUE TITLE
工程生成的静态库问题

### ISSUE THREAD

**Issue by Joker2770** [fffasttime/Gmk1#2]
![libproblem](https://user-images.githubusercontent.com/22749204/44566210-d7ae5d00-a79e-11e8-93ea-7dcc728a7503.PNG)
目录下确实生成了静态库，但是好像链接失败

**Comment by fffasttime** [comment]
看一下vs目录配置，这种问题一般是未找到对应的文件

**Comment by Joker2770** [comment]
我把静态库所处目录包含到库目录还是报无法找到，把目录设置到环境变量也无法找到，我用好几台裸机测试过了

**Comment by fffasttime** [comment]
检查一下boost的版本是否一致，还有vs的编译目标应该是64位的

**Comment by Joker2770** [comment]
是的改成64位就没错了，还有个小问题:怎么让引擎跟人下，用的是gtp协议吗

**Comment by fffasttime** [comment]
有五子棋的piskvork协议，可以加载

**Comment by Joker2770** [comment]
明白了，非常感谢
