### ISSUE TITLE
棋盘是否存在越界问题

### ISSUE THREAD

**Issue by Joker2770** [fffasttime/Gmk1#5]
![error](https://user-images.githubusercontent.com/22749204/45262961-7996a080-b453-11e8-9cfd-edfee0c8b416.PNG)
如上图15x15棋盘中，”turn 15，0“似乎是越界了，请问为什么会造成这样的结果。

**Comment by fffasttime** [comment]
这个值表示三手交换，用--swap3=false禁用三手交换

**Comment by fffasttime** [comment]
代码并没有限制必须在第三手才能输入交换，但是在第一手要求交换时会出现问题
